####################
# Site information #
####################
title:                Sejin's DevDocs                       # Title of the jekyll blog.
tagline:              'Recording what I learned'            # Additional title of the jekyll blog.
description:          'Blog of YourName. Here are some technical stuff. Some notes about development.'
baseurl:              # '/pages/home/'
url:                  https://github.com/ImSejin
logo:                 '/public/logo.png'
version:              1.0.0

#######################
# Site Configurations #
#######################
paginate:             5                                     # The number of articles per page.
paginate_path:        '/pages/home/page:num'                # URI to get pagination.
permalink:            '/pages/:categories/:title'           # It makes URI pretty by erasing file extension.
relative_permalinks:  false                                 # It ensures article links from the index work properly.
sass:
  sass_dir:           /_styles/                             # Directory of saved SCSS files and the files to be compiled.
  style:              compressed                            # Minify CSS files.
search:               true

##############
# Navigation #
##############
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'                                # The path of parent menu must be the first element of array.
    - { Category: '/pages/categories' }
    - { Tag: '/pages/tags' }
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/ImSejin'
category_page: '/blog/categories/'            # Where are categories displayed.
tag_page: '/blog/tags/'                       # Where are tags displayed.

################
# Dependencies #
################
gems:
  - jekyll-paginate
markdown:             kramdown
kramdown:
  input:              GFM
highlighter:          rouge

###########
# Plugins #
###########
mathjax: true                                 # Whether support mathjax.
google_analytics_token:     # 'UA-00000000-1' # Leave blank if you don't want google analytics.
disqus_short_name:        # 'your_short_name' # Leave blank if you don't want disqus.

#######################
# Contact information #
#######################
author:
  name:           Im Sejin
  introduction:   Junior develpoer. <a href="#">here</a>.
  photo:          /public/imgs/sejin.jpg
  gravatar:     https://en.gravatar.com/yourname
  contact:
    github:       http://imsejin.github.io
    # facebook:     
    email:        hackeres123@gmail.com

repo:           https://github.com/codinfox/lanyon-codinfox.github.io
